name: Build Docker Image

on:
  push:
    # Trigger the workflow on any branch or tag
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          SYNCTHING_VERSION=$(grep -oP '(?<=ENV SYNCTHING_VERSION=).*' Dockerfile)
          docker buildx build --platform linux/arm/v7 -t your-image-name:$SYNCTHING_VERSION .
