name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          SYNCTHING_VERSION=$(grep -oP '(?<=ENV SYNCTHING_VERSION=).*' Dockerfile)
          docker buildx build --platform linux/arm/v7 -t savemech/syncthing-arm:$SYNCTHING_VERSION .

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: savemech/syncthing-arm:$SYNCTHING_VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
